version: '2'
services:
  polling-service:
    image: storjlabs/auditor-polling-service
    links:
      - redis
    volumes:
      - "../lib:/polling/lib"
      - "../bin:/polling/bin"
      - "../config.js:/polling/config.js"
    build:
      context: ..
      dockerfile: ./dockerfiles/polling-dev.dockerfile
  worker-service:
    image: storjlabs/auditor-worker-service
    links:
      - redis
      - mongo
    volumes:
      - "../lib:/worker/lib"
      - "../bin:/worker/bin"
      - "../config.js:/worker/config.js"
    build:
      context: ..
      dockerfile: ./dockerfiles/worker.dockerfile
  server:
    image: storjlabs/auditor-server
    links:
      - redis
    volumes:
      - "../lib:/audits-server/lib"
      - "../bin:/audits-server/bin"
      - "../config.js:/audits-server/config.js"
    build:
      context: ..
      dockerfile: ./dockerfiles/server.dockerfile
  redis:
    image: redis
    ports:
      - "6379:6379"
  mongo:
    image: mongo
    ports:
      - "27017:27017"
