version: '2'
services:
  worker-service:
    image: storjlabs/auditor-worker-service
    links:
      - mongo
    volumes:
      - "../lib:/worker/lib"
      - "../bin:/worker/bin"
      - "../config.js:/worker/config.js"
    build:
      context: ..
      dockerfile: ./dockerfiles/worker-dev.dockerfile
    environment:
      - audits_maxConcurrency=200
      - audits_sleepTime=500
      - audits_mongo__uri=mongodb://mongo/storj-bridge-database-name
    # - audits_mongo__options__user=
    # - audits_mongo__options__pass=
      - audits_complex__rpcUrl=http://localhost:8080
    # - audits_complex__rpcUser=
    # - audits_complex__rpcPassword=

  server:
    image: storjlabs/auditor-server
    links:
      - mongo
    volumes:
      - "../lib:/audits-server/lib"
      - "../bin:/audits-server/bin"
      - "../config.js:/audits-server/config.js"
    build:
      context: ..
      dockerfile: ./dockerfiles/server-dev.dockerfile
    environment:
      - audits_server__host=127.0.0.1
      - audits_server__port=8080
      - audits_server__options__name=storj-service-auditor
    # - audits_server__options__certificate=
    # - audits_server__options__key=

  mongo:
    image: mongo
    ports:
      - "27017:27017"
